spring:
  application:
    # 应用名称
    name: gateway
  cloud:
    gateway:
      routes:
      # =====================================
      - id: test-id
        uri: http://localhost:9001
        order: -1
        predicates:
        - Path=/user-provider/**
        filters:
        - StripPrefix=1

server:
  port: 9000


# 配置日志级别，方别调试
logging:
  level:
    org.springframework.cloud.gateway: debug