spring:
  application:
    # 应用名称
    name: gateway
  cloud:
    gateway:
      routes:
      # =====================================
      - id: user-consumer
        uri: http://localhost:9002
        order: -1
        predicates:
        - Path=/user/**
        filters:
        - StripPrefix=1

      - id: user-quartz
        uri: http://localhost:9200
        order: -1
        predicates:
        - Path=/quartz/**
        filters:
        - StripPrefix=1

      - id: equipment-consumer
        uri: http://localhost:9004
        order: -1
        predicates:
          - Path=/equipment/**
        filters:
          - StripPrefix=1

server:
  port: 9000


# 配置日志级别，方别调试
logging:
  level:
    org.springframework.cloud.gateway: debug