spring:
  application:
    name: quartz
  cloud:
    nacos:
      discovery:
        server-addr: 144.202.58.141:8848

  jackson:
    date-format: yyyy-MM-dd HH:mm

feign:
  sentinel:
    enabled: true